// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT104xGyRbA2IB27NfD8dhgIjNsVl5jFk',
    appId: '1:11126289632:web:56f007a06af7fe2af38c85',
    messagingSenderId: '11126289632',
    projectId: 'fir-flutter-codelab-c31a6',
    authDomain: 'fir-flutter-codelab-c31a6.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c31a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc8FjNfpRPI2p6KVXCvZv_cj5-w5GNv4U',
    appId: '1:11126289632:android:e37caea6438b8891f38c85',
    messagingSenderId: '11126289632',
    projectId: 'fir-flutter-codelab-c31a6',
    storageBucket: 'fir-flutter-codelab-c31a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6eAMTMjQT4oBDSZY03_BRsSt2mEnA5m8',
    appId: '1:11126289632:ios:3f430b92dc4cde57f38c85',
    messagingSenderId: '11126289632',
    projectId: 'fir-flutter-codelab-c31a6',
    storageBucket: 'fir-flutter-codelab-c31a6.appspot.com',
    iosClientId: '11126289632-hohqjvbirr7530pmjtnecrdjsoedssl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6eAMTMjQT4oBDSZY03_BRsSt2mEnA5m8',
    appId: '1:11126289632:ios:3f430b92dc4cde57f38c85',
    messagingSenderId: '11126289632',
    projectId: 'fir-flutter-codelab-c31a6',
    storageBucket: 'fir-flutter-codelab-c31a6.appspot.com',
    iosClientId: '11126289632-hohqjvbirr7530pmjtnecrdjsoedssl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
